metric_path: ../../metric/
model_path: ../../models/
processed_path: ../../data/processed/processed.csv
trained_path: ../../data/trained/
val_processed_path: ../../data/processed/val_processed.csv
validation_path: ../../data/validation/validation.csv
